version: '2'
services:
  irhid:
    build: ./irhid
    privileged: true
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.sysfs: '1'
      io.balena.features.procfs: '1'
      io.balena.features.kernel-modules: '1'
